version: '3.8'

services:
  node:
    image: quay.io/prometheus/node-exporter:v1.6.0
  promrelay:
    image: ghcr.io/hhromic/promrelay-exporter:v2.0.0
    networks:
      - default
      - metrics

networks:
  default: {}
  metrics:
    external: true
    name: metrics_default
