global:
  scrape_interval: 15s

scrape_configs:
  - job_name: myapp
    static_configs:
      - targets:
          - myapp:9100  # not accessible by Prometheus directly
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'app_promrelay:8080'  # the relay server address
